// Code generated by gen-accessors; DO NOT EDIT.

package management

// String returns a string representation of Tenant.
func (t *Tenant) String() string {
	return Stringify(t)
}

// String returns a string representation of TenantChangePassword.
func (t *TenantChangePassword) String() string {
	return Stringify(t)
}

// String returns a string representation of TenantGuardianMFAPage.
func (t *TenantGuardianMFAPage) String() string {
	return Stringify(t)
}

// String returns a string representation of TenantErrorPage.
func (t *TenantErrorPage) String() string {
	return Stringify(t)
}

// String returns a string representation of TenantFlags.
func (t *TenantFlags) String() string {
	return Stringify(t)
}

// String returns a string representation of TenantUniversalLogin.
func (t *TenantUniversalLogin) String() string {
	return Stringify(t)
}

// String returns a string representation of TenantUniversalLoginColors.
func (t *TenantUniversalLoginColors) String() string {
	return Stringify(t)
}

// String returns a string representation of TenantDeviceFlow.
func (t *TenantDeviceFlow) String() string {
	return Stringify(t)
}

// String returns a string representation of Job.
func (j *Job) String() string {
	return Stringify(j)
}

// String returns a string representation of List.
func (l *List) String() string {
	return Stringify(l)
}

// String returns a string representation of Rule.
func (r *Rule) String() string {
	return Stringify(r)
}

// String returns a string representation of RuleList.
func (r *RuleList) String() string {
	return Stringify(r)
}

// String returns a string representation of Grant.
func (g *Grant) String() string {
	return Stringify(g)
}

// String returns a string representation of EmailTemplate.
func (e *EmailTemplate) String() string {
	return Stringify(e)
}

// String returns a string representation of Log.
func (l *Log) String() string {
	return Stringify(l)
}

// String returns a string representation of Prompt.
func (p *Prompt) String() string {
	return Stringify(p)
}

// String returns a string representation of BlacklistToken.
func (b *BlacklistToken) String() string {
	return Stringify(b)
}

// String returns a string representation of ResourceServer.
func (r *ResourceServer) String() string {
	return Stringify(r)
}

// String returns a string representation of ResourceServerScope.
func (r *ResourceServerScope) String() string {
	return Stringify(r)
}

// String returns a string representation of ResourceServerList.
func (r *ResourceServerList) String() string {
	return Stringify(r)
}

// String returns a string representation of Role.
func (r *Role) String() string {
	return Stringify(r)
}

// String returns a string representation of Permission.
func (p *Permission) String() string {
	return Stringify(p)
}

// String returns a string representation of RoleList.
func (r *RoleList) String() string {
	return Stringify(r)
}

// String returns a string representation of Client.
func (c *Client) String() string {
	return Stringify(c)
}

// String returns a string representation of ClientJWTConfiguration.
func (c *ClientJWTConfiguration) String() string {
	return Stringify(c)
}

// String returns a string representation of ClientList.
func (c *ClientList) String() string {
	return Stringify(c)
}

// String returns a string representation of Email.
func (e *Email) String() string {
	return Stringify(e)
}

// String returns a string representation of EmailCredentials.
func (e *EmailCredentials) String() string {
	return Stringify(e)
}

// String returns a string representation of CustomDomain.
func (c *CustomDomain) String() string {
	return Stringify(c)
}

// String returns a string representation of CustomDomainVerification.
func (c *CustomDomainVerification) String() string {
	return Stringify(c)
}

// String returns a string representation of Ticket.
func (t *Ticket) String() string {
	return Stringify(t)
}

// String returns a string representation of User.
func (u *User) String() string {
	return Stringify(u)
}

// String returns a string representation of UserIdentity.
func (u *UserIdentity) String() string {
	return Stringify(u)
}

// String returns a string representation of UserList.
func (u *UserList) String() string {
	return Stringify(u)
}

// String returns a string representation of ClientGrant.
func (c *ClientGrant) String() string {
	return Stringify(c)
}

// String returns a string representation of ClientGrantList.
func (c *ClientGrantList) String() string {
	return Stringify(c)
}

// String returns a string representation of DailyStat.
func (d *DailyStat) String() string {
	return Stringify(d)
}

// String returns a string representation of MultiFactor.
func (m *MultiFactor) String() string {
	return Stringify(m)
}

// String returns a string representation of MultiFactorSMSTemplate.
func (m *MultiFactorSMSTemplate) String() string {
	return Stringify(m)
}

// String returns a string representation of MultiFactorProviderAmazonSNS.
func (m *MultiFactorProviderAmazonSNS) String() string {
	return Stringify(m)
}

// String returns a string representation of MultiFactorProviderTwilio.
func (m *MultiFactorProviderTwilio) String() string {
	return Stringify(m)
}

// String returns a string representation of MultiFactorSMS.
func (m *MultiFactorSMS) String() string {
	return Stringify(m)
}

// String returns a string representation of MultiFactorPush.
func (m *MultiFactorPush) String() string {
	return Stringify(m)
}

// String returns a string representation of MultiFactorEmail.
func (m *MultiFactorEmail) String() string {
	return Stringify(m)
}

// String returns a string representation of MultiFactorDUO.
func (m *MultiFactorDUO) String() string {
	return Stringify(m)
}

// String returns a string representation of MultiFactorOTP.
func (m *MultiFactorOTP) String() string {
	return Stringify(m)
}

// String returns a string representation of Connection.
func (c *Connection) String() string {
	return Stringify(c)
}

// String returns a string representation of ConnectionOptions.
func (c *ConnectionOptions) String() string {
	return Stringify(c)
}

// String returns a string representation of ConnectionOptionsTotp.
func (c *ConnectionOptionsTotp) String() string {
	return Stringify(c)
}

// String returns a string representation of ConnectionList.
func (c *ConnectionList) String() string {
	return Stringify(c)
}

// String returns a string representation of RuleConfig.
func (r *RuleConfig) String() string {
	return Stringify(r)
}

// String returns a string representation of Branding.
func (b *Branding) String() string {
	return Stringify(b)
}

// String returns a string representation of BrandingColors.
func (b *BrandingColors) String() string {
	return Stringify(b)
}

// String returns a string representation of BrandingFont.
func (b *BrandingFont) String() string {
	return Stringify(b)
}
